const {getLog} = require("../serverModules/logger");

/**
 * @openapi
 * /api/logs:
 *   get:
 *     summary: Retrieves the server's logs
 *     description: Returns a list of logs generated by the server.
 *     operationId: getLogs
 *     responses:
 *       200:
 *         description: The most recent in-memory log entries (at most 2000).
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 logs:
 *                   type: array
 *                   description: Log entries, oldest first. Each entry is the list of arguments passed to the logger.
 *                   items:
 *                     type: array
 *                     items: {}
 *               required:
 *                 - logs
 */
module.exports = (req, res) => {
    res.json({ logs: getLog() });
};
