const {getLog} = require("../serverModules/logger");

/**
 * @openapi
 * /api/logs:
 *   get:
 *     summary: Retrieves the server's logs
 *     description: Returns a list of logs generated by the server.
 *     operationId: getLogs
 *     responses:
 *       200:
 *         description: A list of server logs.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 logs:
 *                   type: array
 *                   items:
 *                     type: array
 *                     items: true
 *                   description: Server log entries (variadic argument tuples as recorded by the logger)
 *               required:
 *                 - logs
 */
module.exports = (req, res) => {
    res.json({ logs: getLog() });
};
